# Generated by Django 4.2.3 on 2023-08-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_name_category_names_delete_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='names',
            new_name='name',
        ),
    ]
