# Generated by Django 4.2.3 on 2023-08-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_names_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='names',
        ),
    ]
